name = "GeoThermalCloud"
uuid = "9b555b37-faa4-4dca-b31f-51f0aad2d23b"
authors = ["Velimir V Vesselinov (monty) <velimir.vesselinov@gmail.com>"]
version = "0.1.4"

[deps]
Cairo = "159f3aea-2a34-519c-b102-8c37f9878175"
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
DocumentFunction = "e1f3b4f0-2dc4-57d3-83f7-d4b7faf3b05b"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
Fontconfig = "186bb1d3-e1f7-5a2c-a377-96d770f13627"
GMT = "5752ebe1-31b9-557e-87aa-f909b540aa54"
Gadfly = "c91e804a-d5a3-530f-b6f0-dfbca275c004"
Geodesy = "0ef565a4-170c-5f04-8de2-149903a85f3d"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
JLD = "4138dd39-2aa7-5051-a626-17a0bb65d9c8"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
Kriging = "6133562b-a8e8-5ea3-954b-37642b766dad"
Mads = "d6bdc55b-bd94-5012-933c-1f73fc2ee992"
NMFk = "e40cd9e2-a1df-5d90-a1fa-603fdc3dbdd8"
NTFk = "1226e131-0b97-51f8-8a3f-c1798118cd52"
SVR = "22bb73d7-edb2-5785-ba1e-7d60d6824784"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
XLSX = "fdbf4ff8-1666-58a4-91e7-1b58723a45e0"

[compat]
Cairo = "1"
Clustering = "0.14, 0.15"
DocumentFunction = "1"
FileIO = "1"
Fontconfig = "0.4, 0.5"
GMT = "0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.42"
Gadfly = "1"
Geodesy = "1"
IJulia = "1"
JLD = "0.10, 0.11, 0.12, 0.13"
JLD2 = "0.2, 0.3, 0.4, 0.5"
Kriging = "1.1"
Mads = "1.1"
NMFk = "1"
NTFk = "1"
SVR = "1"
XLSX = "0.7, 0.8, 0.9"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
